/**
 * UPTIMAIZE platform — command center dataset.
 *
 * A single deterministic snapshot that drives every panel in `app/(platform)`.
 * It is intentionally isolated behind `getCommandCenterData()` so the aggregation
 * layer (Prisma + agent telemetry) can replace the body without touching the UI.
 */

import type {
    ActivityEvent,
    Approval,
    CommandCenterData,
    Deliverable,
    Kpi,
    Partner,
    PlatformAgent,
    PlatformAlert,
    RevenueLeak,
    SavingsCategory,
    ShadowOp,
    TrendPoint,
    Workflow,
} from './types';

const PERIOD = { label: 'May 18 – May 25, 2025', comparison: 'vs May 11 – May 17, 2025' };

const KPIS: Kpi[] = [
    {
        id: 'revenue-protected',
        label: 'Revenue Protected',
        value: '$2.47',
        unit: 'M',
        delta: '18.6%',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'primary',
        icon: 'shield',
    },
    {
        id: 'money-saved',
        label: 'Money Saved',
        value: '$1.23',
        unit: 'M',
        delta: '24.3%',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'primary',
        icon: 'dollar',
    },
    {
        id: 'hours-reclaimed',
        label: 'Hours Reclaimed',
        value: '312.5',
        delta: '16.9%',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'gold',
        icon: 'clock',
    },
    {
        id: 'agents-active',
        label: 'Agents Active',
        value: '24',
        of: '/ 70',
        delta: '4',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'primary',
        icon: 'bot',
    },
    {
        id: 'workflows-running',
        label: 'Workflows Running',
        value: '18',
        delta: '3',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'gold',
        icon: 'network',
    },
    {
        id: 'system-health',
        label: 'System Health',
        value: '98.7',
        unit: '%',
        delta: '2.1pp',
        deltaLabel: 'vs last 7 days',
        trend: 'up',
        tone: 'green',
        icon: 'pulse',
        note: 'Excellent',
    },
];

const AGENTS: PlatformAgent[] = [
    {
        id: 'shadow-ops-detector',
        name: 'Shadow Ops Detector',
        description: 'Monitors for hidden manual work',
        status: 'active',
        tasks: 1248,
        approvals: 3,
        performance: 98.2,
        leaksDetected: 24,
        leaksClosed: 18,
        trend: [12, 18, 15, 22, 19, 27, 31, 29, 34, 38],
        impact: 'high',
    },
    {
        id: 'revenue-leak-hunter',
        name: 'Revenue Leak Hunter',
        description: 'Finds leaks and lost revenue',
        status: 'active',
        tasks: 2317,
        approvals: 5,
        performance: 97.6,
        leaksDetected: 21,
        leaksClosed: 16,
        trend: [20, 24, 21, 28, 33, 30, 36, 41, 39, 45],
        impact: 'high',
    },
    {
        id: 'workflow-optimizer',
        name: 'Workflow Optimizer',
        description: 'Optimizes and streamlines flows',
        status: 'active',
        tasks: 892,
        approvals: 2,
        performance: 96.9,
        leaksDetected: 18,
        leaksClosed: 14,
        trend: [9, 14, 12, 17, 16, 21, 19, 24, 26, 25],
        impact: 'medium',
    },
    {
        id: 'approvals-intelligence',
        name: 'Approvals Intelligence',
        description: 'Routes and prioritizes approvals',
        status: 'active',
        tasks: 1105,
        approvals: 7,
        performance: 96.4,
        leaksDetected: 17,
        leaksClosed: 12,
        trend: [14, 11, 18, 16, 22, 20, 25, 23, 28, 30],
        impact: 'medium',
    },
    {
        id: 'data-reconciler',
        name: 'Data Reconciler',
        description: 'Validates and reconciles data',
        status: 'idle',
        tasks: 256,
        approvals: 0,
        performance: 99.1,
        leaksDetected: 9,
        leaksClosed: 8,
        trend: [6, 8, 7, 10, 9, 12, 11, 13, 12, 14],
        impact: 'low',
    },
    {
        id: 'report-generator',
        name: 'Report Generator',
        description: 'Builds and delivers insights',
        status: 'active',
        tasks: 664,
        approvals: 1,
        performance: 97.8,
        leaksDetected: 7,
        leaksClosed: 6,
        trend: [8, 10, 9, 13, 12, 15, 17, 16, 19, 21],
        impact: 'low',
    },
    {
        id: 'contract-sentinel',
        name: 'Contract Sentinel',
        description: 'Watches renewals and contract terms',
        status: 'active',
        tasks: 418,
        approvals: 2,
        performance: 95.7,
        leaksDetected: 11,
        leaksClosed: 7,
        trend: [5, 9, 8, 12, 14, 13, 18, 17, 20, 22],
        impact: 'medium',
    },
    {
        id: 'forecast-engine',
        name: 'Forecast Engine',
        description: 'Projects savings and revenue at risk',
        status: 'active',
        tasks: 537,
        approvals: 0,
        performance: 94.9,
        leaksDetected: 6,
        leaksClosed: 5,
        trend: [11, 13, 12, 16, 15, 18, 21, 20, 23, 26],
        impact: 'low',
    },
    {
        id: 'onboarding-concierge',
        name: 'Onboarding Concierge',
        description: 'Runs partner onboarding end to end',
        status: 'paused',
        tasks: 143,
        approvals: 1,
        performance: 93.4,
        leaksDetected: 3,
        leaksClosed: 3,
        trend: [4, 6, 5, 7, 6, 8, 7, 9, 8, 10],
        impact: 'low',
    },
    {
        id: 'compliance-watchdog',
        name: 'Compliance Watchdog',
        description: 'Flags policy and audit exceptions',
        status: 'active',
        tasks: 389,
        approvals: 4,
        performance: 96.1,
        leaksDetected: 8,
        leaksClosed: 6,
        trend: [7, 9, 11, 10, 14, 13, 16, 18, 17, 20],
        impact: 'medium',
    },
];

const LEAKS: RevenueLeak[] = [
    {
        id: 'L-78421',
        name: 'Duplicate Data Entry',
        impact: 320_000,
        source: 'CRM / Manual Work',
        partner: 'SouthRex Solutions',
        severity: 'high',
        status: 'investigating',
        detectedAt: 'May 24, 2025 9:42 AM',
        detectedBy: 'Revenue Leak Hunter',
        assignee: 'Priya Shah',
        description:
            'Duplicate data entry in CRM causing inflated opportunity values and inaccurate forecasting across Sales Operations.',
        nextStep:
            'Review and validate affected records, then apply the deduplication rule to prevent recurrence.',
        evidence: [
            { name: 'duplicate_records.csv', size: '24.8 KB' },
            { name: 'impact_analysis.pdf', size: '148 KB' },
            { name: 'workflow_trace.json', size: '86.2 KB' },
        ],
    },
    {
        id: 'L-78398',
        name: 'Untracked Approvals',
        impact: 280_000,
        source: 'Shadow Ops',
        partner: 'AutoPro Motors',
        severity: 'high',
        status: 'open',
        detectedAt: 'May 24, 2025 7:15 AM',
        detectedBy: 'Shadow Ops Detector',
        assignee: 'Marcus Bell',
        description:
            'Approvals routed over email bypass the approval ledger, leaving spend unreconciled at month end.',
        nextStep: 'Route the email approval path through Approvals Intelligence and backfill the ledger.',
        evidence: [
            { name: 'approval_gaps.csv', size: '18.1 KB' },
            { name: 'email_trace.json', size: '64.4 KB' },
        ],
    },
    {
        id: 'L-78355',
        name: 'Tool Overlap',
        impact: 210_000,
        source: 'Disconnected Systems',
        partner: 'PowerGrid Energy',
        severity: 'medium',
        status: 'investigating',
        detectedAt: 'May 23, 2025 4:02 PM',
        detectedBy: 'Workflow Optimizer',
        assignee: 'Dana Cole',
        description:
            'Three overlapping SaaS tools cover the same scheduling function across two business units.',
        nextStep: 'Consolidate onto the primary scheduler and cancel the two redundant licenses at renewal.',
        evidence: [
            { name: 'license_inventory.xlsx', size: '212 KB' },
            { name: 'usage_overlap.pdf', size: '96.7 KB' },
        ],
    },
    {
        id: 'L-78310',
        name: 'Missed Follow-ups',
        impact: 190_000,
        source: 'Process Gaps',
        partner: 'NextLevel Services',
        severity: 'medium',
        status: 'open',
        detectedAt: 'May 23, 2025 11:28 AM',
        detectedBy: 'Revenue Leak Hunter',
        assignee: 'Priya Shah',
        description:
            'Inbound leads older than 48 hours receive no second touch, costing an estimated 14 opportunities per month.',
        nextStep: 'Enable the 48-hour nurture sequence and alert owners on SLA breach.',
        evidence: [{ name: 'followup_sla.csv', size: '31.9 KB' }],
    },
    {
        id: 'L-78287',
        name: 'Reporting Delays',
        impact: 150_000,
        source: 'Poor Visibility',
        partner: 'Elite Trim Pros',
        severity: 'low',
        status: 'open',
        detectedAt: 'May 22, 2025 3:47 PM',
        detectedBy: 'Report Generator',
        assignee: 'Marcus Bell',
        description:
            'Weekly operating reports arrive four days late, so corrective action lands a full cycle behind.',
        nextStep: 'Schedule automated Monday 7:00 AM generation and delivery.',
        evidence: [{ name: 'report_latency.csv', size: '12.4 KB' }],
    },
    {
        id: 'L-78240',
        name: 'Contract Leakage',
        impact: 120_000,
        source: 'Renewal Gaps',
        partner: 'Triple S Solar',
        severity: 'medium',
        status: 'resolved',
        detectedAt: 'May 20, 2025 10:05 AM',
        detectedBy: 'Contract Sentinel',
        resolvedOn: 'May 22, 2025',
        assignee: 'Dana Cole',
        description:
            'Auto-renewing contracts renewed below the indexed rate for six accounts.',
        nextStep: 'Rate index applied at renewal; monitoring for recurrence over the next two cycles.',
        evidence: [{ name: 'renewal_variance.xlsx', size: '148 KB' }],
    },
    {
        id: 'L-78201',
        name: 'Shadow Ops — Manual Report Build',
        impact: 230_000,
        source: 'Shadow Ops',
        partner: 'Elite Trim Pros',
        severity: 'medium',
        status: 'resolved',
        detectedAt: 'May 19, 2025 8:33 AM',
        detectedBy: 'Shadow Ops Detector',
        resolvedOn: 'May 23, 2025',
        assignee: 'Priya Shah',
        description:
            'An analyst rebuilt the same operations report by hand every Monday, 22 hours per month.',
        nextStep: 'Replaced with a scheduled Report Generator workflow; hours redeployed to analysis.',
        evidence: [{ name: 'shadow_trace.json', size: '77.5 KB' }],
    },
    {
        id: 'L-78164',
        name: 'Duplicate Tool License',
        impact: 127_000,
        source: 'Disconnected Systems',
        partner: 'SouthRex Solutions',
        severity: 'low',
        status: 'resolved',
        detectedAt: 'May 18, 2025 1:12 PM',
        detectedBy: 'Workflow Optimizer',
        resolvedOn: 'May 21, 2025',
        assignee: 'Dana Cole',
        description: 'Two departments held separate contracts for the same analytics platform.',
        nextStep: 'Merged into one enterprise agreement; savings booked to the current quarter.',
        evidence: [{ name: 'license_merge.pdf', size: '54.2 KB' }],
    },
    {
        id: 'L-78129',
        name: 'Unbilled Service Hours',
        impact: 165_000,
        source: 'Process Gaps',
        partner: 'AutoPro Motors',
        severity: 'high',
        status: 'resolved',
        detectedAt: 'May 18, 2025 9:20 AM',
        detectedBy: 'Revenue Leak Hunter',
        resolvedOn: 'May 24, 2025',
        assignee: 'Marcus Bell',
        description: 'Field service hours logged outside the billing window were never invoiced.',
        nextStep: 'Billing sync now runs nightly; historical hours recovered and invoiced.',
        evidence: [{ name: 'unbilled_hours.csv', size: '42.6 KB' }],
    },
];

const APPROVALS: Approval[] = [
    {
        id: 'A-5021',
        title: 'Refund Over $5,000',
        partner: 'SouthRex Solutions',
        amount: 5850,
        waiting: '12m',
        urgency: 'critical',
    },
    {
        id: 'A-5019',
        title: 'Write-off Approval',
        partner: 'AutoPro Motors',
        amount: 3200,
        waiting: '28m',
        urgency: 'critical',
    },
    {
        id: 'A-5016',
        title: 'Vendor Exception',
        partner: 'PowerGrid Energy',
        amount: 7450,
        waiting: '45m',
        urgency: 'warning',
    },
    {
        id: 'A-5012',
        title: 'Manual Discount',
        partner: 'Elite Trim Pros',
        amount: 2100,
        waiting: '1h',
        urgency: 'warning',
    },
    {
        id: 'A-5008',
        title: 'Data Update Request',
        partner: 'NextLevel Services',
        amount: 1650,
        waiting: '2h',
        urgency: 'normal',
    },
    {
        id: 'A-5003',
        title: 'Contract Rate Override',
        partner: 'Triple S Solar',
        amount: 4300,
        waiting: '3h',
        urgency: 'normal',
    },
    {
        id: 'A-4998',
        title: 'Credit Memo Issue',
        partner: 'SouthRex Solutions',
        amount: 1280,
        waiting: '4h',
        urgency: 'normal',
    },
];

const PARTNERS: Partner[] = [
    {
        id: 'southrex',
        name: 'SouthRex Solutions',
        health: 'healthy',
        revenueProtected: 612_000,
        moneySaved: 318_000,
        leaksDetected: 8,
        leaksClosed: 6,
        agents: 6,
        workflows: 5,
        trend: [38, 44, 41, 52, 49, 58, 63],
        tone: 'primary',
        since: 'Aug 2024',
    },
    {
        id: 'autopro',
        name: 'AutoPro Motors',
        health: 'healthy',
        revenueProtected: 487_000,
        moneySaved: 241_000,
        leaksDetected: 6,
        leaksClosed: 5,
        agents: 5,
        workflows: 4,
        trend: [31, 29, 36, 34, 42, 45, 48],
        tone: 'primary',
        since: 'Oct 2024',
    },
    {
        id: 'elite-trim',
        name: 'Elite Trim Pros',
        health: 'at_risk',
        revenueProtected: 312_000,
        moneySaved: 158_000,
        leaksDetected: 4,
        leaksClosed: 2,
        agents: 4,
        workflows: 3,
        trend: [28, 33, 26, 31, 24, 27, 22],
        tone: 'gold',
        since: 'Jan 2025',
    },
    {
        id: 'powergrid',
        name: 'PowerGrid Energy',
        health: 'healthy',
        revenueProtected: 298_000,
        moneySaved: 147_000,
        leaksDetected: 3,
        leaksClosed: 3,
        agents: 4,
        workflows: 3,
        trend: [19, 23, 22, 27, 29, 33, 36],
        tone: 'gold',
        since: 'Nov 2024',
    },
    {
        id: 'nextlevel',
        name: 'NextLevel Services',
        health: 'watch',
        revenueProtected: 265_000,
        moneySaved: 129_000,
        leaksDetected: 2,
        leaksClosed: 1,
        agents: 3,
        workflows: 2,
        trend: [24, 21, 26, 23, 28, 25, 30],
        tone: 'pink',
        since: 'Feb 2025',
    },
    {
        id: 'triple-s',
        name: 'Triple S Solar',
        health: 'healthy',
        revenueProtected: 213_000,
        moneySaved: 104_000,
        leaksDetected: 2,
        leaksClosed: 2,
        agents: 2,
        workflows: 1,
        trend: [15, 18, 17, 21, 20, 24, 27],
        tone: 'pink',
        since: 'Mar 2025',
    },
];

const ACTIVITY: ActivityEvent[] = [
    {
        id: 'E-9001',
        kind: 'leak',
        title: 'Revenue Leak detected: Duplicate Data Entry',
        context: 'SouthRex Solutions',
        meta: 'Impact: $320K',
        at: '12m ago',
    },
    {
        id: 'E-9000',
        kind: 'workflow',
        title: 'Workflow Optimization completed',
        context: 'AutoPro Motors',
        meta: '14 automations updated · 3.2s',
        at: '26m ago',
    },
    {
        id: 'E-8999',
        kind: 'approval',
        title: 'Approval requested: Refund Over $5,000',
        context: 'SouthRex Solutions',
        meta: '$5,850',
        at: '41m ago',
    },
    {
        id: 'E-8998',
        kind: 'shadow',
        title: 'Shadow Ops detected: Manual Report Build',
        context: 'Elite Trim Pros',
        meta: 'Impact: $1,200/mo',
        at: '1h ago',
    },
    {
        id: 'E-8997',
        kind: 'data',
        title: 'Data Reconciliation completed',
        context: 'PowerGrid Energy',
        meta: '3,247 records',
        at: '2h ago',
    },
    {
        id: 'E-8996',
        kind: 'report',
        title: 'Weekly Ops Summary generated',
        context: 'All partners',
        meta: 'PDF report',
        at: '3h ago',
    },
    {
        id: 'E-8995',
        kind: 'approval',
        title: 'Approval auto-approved under policy',
        context: 'NextLevel Services',
        meta: '24 requests',
        at: '5h ago',
    },
    {
        id: 'E-8994',
        kind: 'leak',
        title: 'Revenue Leak resolved: Duplicate Tool License',
        context: 'SouthRex Solutions',
        meta: '$127K saved',
        at: '6h ago',
    },
];

const DELIVERABLES: Deliverable[] = [
    {
        id: 'D-401',
        name: 'Executive Summary',
        period: 'May 18 – May 25, 2025',
        format: 'PDF',
        size: '2.4 MB',
        generatedOn: 'May 25, 2025',
    },
    {
        id: 'D-400',
        name: 'Revenue Leak Analysis',
        period: 'May 18 – May 25, 2025',
        format: 'XLSX',
        size: '1.8 MB',
        generatedOn: 'May 25, 2025',
    },
    {
        id: 'D-399',
        name: 'Workflow Performance Report',
        period: 'May 18 – May 25, 2025',
        format: 'PDF',
        size: '3.1 MB',
        generatedOn: 'May 24, 2025',
    },
    {
        id: 'D-398',
        name: 'ROI Impact Summary',
        period: 'May 2025 month to date',
        format: 'PPTX',
        size: '4.2 MB',
        generatedOn: 'May 24, 2025',
    },
    {
        id: 'D-397',
        name: 'Agent Activity Summary',
        period: 'May 18 – May 25, 2025',
        format: 'PDF',
        size: '1.2 MB',
        generatedOn: 'May 23, 2025',
    },
    {
        id: 'D-396',
        name: 'Approvals & Exceptions Log',
        period: 'May 2025 month to date',
        format: 'CSV',
        size: '640 KB',
        generatedOn: 'May 23, 2025',
    },
];

const ALERTS: PlatformAlert[] = [
    {
        id: 'N-701',
        level: 'critical',
        title: 'High severity leak detected: Duplicate Data Entry',
        context: 'Impact: $320K · SouthRex Solutions',
        at: '12m ago',
    },
    {
        id: 'N-700',
        level: 'warning',
        title: 'System health degraded in Shadow Ops Detector',
        context: 'Current: 98.7% · threshold 99.0%',
        at: '26m ago',
    },
    {
        id: 'N-699',
        level: 'warning',
        title: 'Approval SLA at risk: Refund Over $5,000',
        context: 'Response due in 18m',
        at: '42m ago',
    },
    {
        id: 'N-698',
        level: 'info',
        title: 'Unusual activity detected in Data Reconciler',
        context: 'Investigating — no action required yet',
        at: '1h ago',
    },
    {
        id: 'N-697',
        level: 'warning',
        title: 'Partner health dropped: Elite Trim Pros',
        context: 'Healthy → At Risk · 2 leaks open',
        at: '3h ago',
    },
    {
        id: 'N-696',
        level: 'success',
        title: 'Revenue Leak resolved: Duplicate Tool License',
        context: '$127K recovered · SouthRex Solutions',
        at: '6h ago',
    },
    {
        id: 'N-695',
        level: 'warning',
        title: 'Workflow paused: Invoice Exception Handling',
        context: 'Elite Trim Pros · success rate 89.7%',
        at: '8h ago',
    },
    {
        id: 'N-694',
        level: 'info',
        title: 'New shadow op detected: Email-based Approvals',
        context: 'AutoPro Motors · 26 hrs/mo',
        at: '11h ago',
    },
    {
        id: 'N-693',
        level: 'success',
        title: 'Revenue Leak resolved: Unbilled Service Hours',
        context: '$165K recovered · AutoPro Motors',
        at: '14h ago',
    },
    {
        id: 'N-692',
        level: 'info',
        title: 'Agent paused by operator: Onboarding Concierge',
        context: 'Scheduled maintenance window',
        at: '18h ago',
    },
    {
        id: 'N-691',
        level: 'warning',
        title: 'Approval volume above forecast',
        context: '7 pending · 2 breaching SLA within the hour',
        at: '21h ago',
    },
    {
        id: 'N-690',
        level: 'success',
        title: 'Weekly deliverables published',
        context: '6 reports delivered to 6 partners',
        at: '1d ago',
    },
];

const SHADOW_OPS: ShadowOp[] = [
    {
        id: 'S-330',
        name: 'Manual Report Build',
        partner: 'Elite Trim Pros',
        system: 'Spreadsheets',
        hoursPerMonth: 22,
        costPerMonth: 1200,
        status: 'eliminated',
        detectedOn: 'May 19, 2025',
    },
    {
        id: 'S-329',
        name: 'Copy-paste CRM Updates',
        partner: 'SouthRex Solutions',
        system: 'CRM',
        hoursPerMonth: 38,
        costPerMonth: 2450,
        status: 'automating',
        detectedOn: 'May 21, 2025',
    },
    {
        id: 'S-328',
        name: 'Email-based Approvals',
        partner: 'AutoPro Motors',
        system: 'Email',
        hoursPerMonth: 26,
        costPerMonth: 1780,
        status: 'detected',
        detectedOn: 'May 24, 2025',
    },
    {
        id: 'S-327',
        name: 'Manual Invoice Matching',
        partner: 'PowerGrid Energy',
        system: 'ERP',
        hoursPerMonth: 31,
        costPerMonth: 2100,
        status: 'automating',
        detectedOn: 'May 22, 2025',
    },
    {
        id: 'S-326',
        name: 'Offline Schedule Reconciliation',
        partner: 'NextLevel Services',
        system: 'Scheduling',
        hoursPerMonth: 18,
        costPerMonth: 940,
        status: 'detected',
        detectedOn: 'May 23, 2025',
    },
    {
        id: 'S-325',
        name: 'Duplicate Data Entry — Field Ops',
        partner: 'Triple S Solar',
        system: 'Field App / CRM',
        hoursPerMonth: 24,
        costPerMonth: 1310,
        status: 'automating',
        detectedOn: 'May 20, 2025',
    },
];

const WORKFLOWS: Workflow[] = [
    {
        id: 'W-120',
        name: 'Lead Intake & Routing',
        partner: 'SouthRex Solutions',
        trigger: 'Form submission',
        runs: 412,
        successRate: 98.4,
        avgDurationSec: 3.2,
        status: 'running',
        lastRun: '4m ago',
        hoursSaved: 61,
    },
    {
        id: 'W-119',
        name: 'Approval Routing',
        partner: 'AutoPro Motors',
        trigger: 'Threshold breach',
        runs: 286,
        successRate: 96.1,
        avgDurationSec: 1.8,
        status: 'running',
        lastRun: '11m ago',
        hoursSaved: 44,
    },
    {
        id: 'W-118',
        name: 'Nightly Data Reconciliation',
        partner: 'PowerGrid Energy',
        trigger: 'Schedule · 02:00',
        runs: 31,
        successRate: 99.1,
        avgDurationSec: 42.6,
        status: 'scheduled',
        lastRun: '9h ago',
        hoursSaved: 38,
    },
    {
        id: 'W-117',
        name: 'Weekly Executive Report',
        partner: 'All partners',
        trigger: 'Schedule · Mon 07:00',
        runs: 8,
        successRate: 100,
        avgDurationSec: 96.4,
        status: 'scheduled',
        lastRun: '2d ago',
        hoursSaved: 27,
    },
    {
        id: 'W-116',
        name: 'Renewal Watch',
        partner: 'Triple S Solar',
        trigger: 'Contract event',
        runs: 54,
        successRate: 94.8,
        avgDurationSec: 5.1,
        status: 'running',
        lastRun: '38m ago',
        hoursSaved: 19,
    },
    {
        id: 'W-115',
        name: 'Follow-up Nurture Sequence',
        partner: 'NextLevel Services',
        trigger: 'SLA breach',
        runs: 147,
        successRate: 92.3,
        avgDurationSec: 2.4,
        status: 'running',
        lastRun: '22m ago',
        hoursSaved: 33,
    },
    {
        id: 'W-114',
        name: 'Invoice Exception Handling',
        partner: 'Elite Trim Pros',
        trigger: 'ERP exception',
        runs: 63,
        successRate: 89.7,
        avgDurationSec: 7.9,
        status: 'paused',
        lastRun: '1d ago',
        hoursSaved: 12,
    },
    {
        id: 'W-113',
        name: 'Onboarding Checklist',
        partner: 'SouthRex Solutions',
        trigger: 'New account',
        runs: 12,
        successRate: 100,
        avgDurationSec: 18.3,
        status: 'draft',
        lastRun: '4d ago',
        hoursSaved: 9,
    },
];

const TREND: TrendPoint[] = [
    { date: 'May 18', revenueProtected: 0.42, moneySaved: 0.21 },
    { date: 'May 19', revenueProtected: 0.98, moneySaved: 0.44 },
    { date: 'May 20', revenueProtected: 1.42, moneySaved: 0.58 },
    { date: 'May 21', revenueProtected: 1.88, moneySaved: 0.72 },
    { date: 'May 22', revenueProtected: 2.31, moneySaved: 1.12 },
    { date: 'May 23', revenueProtected: 2.12, moneySaved: 0.98 },
    { date: 'May 24', revenueProtected: 2.38, moneySaved: 1.16 },
    { date: 'May 25', revenueProtected: 2.47, moneySaved: 1.23 },
];

const SAVINGS_BREAKDOWN: SavingsCategory[] = [
    { label: 'Manual work reduced', value: 420_000, share: 34.1, tone: 'primary' },
    { label: 'Shadow ops eliminated', value: 310_000, share: 25.2, tone: 'pink' },
    { label: 'Duplicate work removed', value: 245_000, share: 19.9, tone: 'gold' },
    { label: 'Approval acceleration', value: 165_000, share: 13.4, tone: 'blue' },
    { label: 'Workflow optimization', value: 80_000, share: 6.5, tone: 'green' },
];

const EXECUTIVE_SUMMARY =
    'This week UPTIMAIZE protected $2.47M in revenue and returned $1.23M in savings across 18 active workflows. ' +
    'The agent fleet detected 9 revenue leaks worth $1.79M and closed 5 of them, while Shadow Ops surfaced 6 hidden ' +
    'manual processes costing $9.8K per month. Your teams reclaimed 312.5 hours — a 16.9% increase over last week — ' +
    'and automation success held at 94.2% with system health at 98.7%.';

const DATA: CommandCenterData = {
    generatedAt: '2025-05-25T09:42:00.000Z',
    period: PERIOD,
    executiveSummary: EXECUTIVE_SUMMARY,
    kpis: KPIS,
    agents: AGENTS,
    leaks: LEAKS,
    approvals: APPROVALS,
    partners: PARTNERS,
    activity: ACTIVITY,
    deliverables: DELIVERABLES,
    alerts: ALERTS,
    shadowOps: SHADOW_OPS,
    workflows: WORKFLOWS,
    trend: TREND,
    savingsBreakdown: SAVINGS_BREAKDOWN,
    workflowPerformance: {
        totalRuns: 142,
        completed: 118,
        exceptions: 14,
        inProgress: 10,
        automationSuccessRate: 94.2,
        successDelta: '6.1%',
    },
    roi: {
        multiple: 7.4,
        previousMultiple: 6.2,
        investment: 166_000,
        returned: 1_230_000,
        hoursReclaimed: 312.5,
        paybackDays: 34,
    },
    systemStatus: { label: 'All systems operational', healthy: true },
};

/** The full command center snapshot. Replace the body to wire real telemetry. */
export function getCommandCenterData(): CommandCenterData {
    return DATA;
}

/** Look up a single leak for the investigation drawer. */
export function getLeak(id: string) {
    return DATA.leaks.find((leak) => leak.id === id);
}
